/** Kids Add/수정 모달 평상시 장식. 폴더 전체 사용. 스키마/권한과 무관. */

export const KIDS_ADD_DECOS: { src: string; className: string }[] = [
  { src: '/family-calendar/add-emojis/cloud.png', className: 'top-1 left-1/2 w-14 -translate-x-1/2' },
  { src: '/family-calendar/add-emojis/book.png', className: 'top-3 left-3 w-10 -rotate-12' },
  { src: '/family-calendar/add-emojis/rainbow-house.png', className: 'top-2 right-3 w-16 rotate-6' },
  { src: '/family-calendar/add-emojis/puppy.png', className: 'top-14 right-2 w-9 rotate-12' },
  { src: '/family-calendar/add-emojis/stroller.png', className: 'top-12 right-16 w-8 -rotate-6' },
  { src: '/family-calendar/add-emojis/rainbow.png', className: 'top-10 left-14 w-12 rotate-[-10deg]' },
  { src: '/family-calendar/add-emojis/earth.png', className: 'top-28 left-1 w-9' },
  { src: '/family-calendar/add-emojis/earth-stars.png', className: 'top-40 left-2 w-10 rotate-6' },
  { src: '/family-calendar/add-emojis/saturn-big.png', className: 'top-24 right-0 w-16 rotate-[-8deg]' },
  { src: '/family-calendar/add-emojis/saturn-small.png', className: 'top-44 right-1 w-9 rotate-12' },
  { src: '/family-calendar/add-emojis/saturn-star.png', className: 'bottom-28 right-2 w-11 -rotate-6' },
  { src: '/family-calendar/add-emojis/rocket-2.png', className: 'top-36 left-0 w-10 rotate-[-20deg]' },
  { src: '/family-calendar/add-emojis/rocket-small.png', className: 'bottom-36 right-0 w-8 rotate-[24deg]' },
  { src: '/family-calendar/add-emojis/moon.png', className: 'top-20 left-20 w-7 -rotate-12' },
  { src: '/family-calendar/add-emojis/sun.png', className: 'top-16 right-28 w-8 rotate-6' },
  { src: '/family-calendar/add-emojis/shooting-stars-2.png', className: 'top-8 left-28 w-14 rotate-[-18deg]' },
  { src: '/family-calendar/add-emojis/seven-star.png', className: 'top-32 right-20 w-12' },
  { src: '/family-calendar/add-emojis/stars.png', className: 'bottom-40 left-1 w-10' },
  { src: '/family-calendar/add-emojis/stars-2.png', className: 'bottom-24 right-16 w-10' },
  { src: '/family-calendar/add-emojis/stars-3.png', className: 'top-52 left-16 w-7' },
  { src: '/family-calendar/add-emojis/stars-4.png', className: 'bottom-16 left-20 w-7' },
  { src: '/family-calendar/add-emojis/star.png', className: 'top-6 right-24 w-6 rotate-12' },
  { src: '/family-calendar/add-emojis/star-small.png', className: 'top-2 left-16 w-4' },
  { src: '/family-calendar/add-emojis/purple-star.png', className: 'bottom-20 right-8 w-5' },
  { src: '/family-calendar/add-emojis/firework.png', className: 'top-[7.5rem] left-8 w-10 -rotate-6' },
  { src: '/family-calendar/add-emojis/firework-2.png', className: 'top-[7.5rem] right-10 w-10 rotate-6' },
  { src: '/family-calendar/add-emojis/ghost.png', className: 'bottom-32 left-3 w-8 rotate-[-8deg]' },
  { src: '/family-calendar/add-emojis/ghost-2.png', className: 'bottom-12 right-3 w-8 rotate-12' },
  { src: '/family-calendar/add-emojis/robot.png', className: 'bottom-8 left-8 w-8' },
  { src: '/family-calendar/add-emojis/heart.png', className: 'bottom-10 left-28 w-6' },
  { src: '/family-calendar/add-emojis/mic.png', className: 'bottom-28 left-14 w-7 rotate-6' },
  { src: '/family-calendar/add-emojis/books.png', className: 'bottom-16 left-2 w-8 -rotate-6' },
  { src: '/family-calendar/add-emojis/milk.png', className: 'bottom-8 right-24 w-7' },
  { src: '/family-calendar/add-emojis/bicycle.png', className: 'bottom-4 left-16 w-10' },
  { src: '/family-calendar/add-emojis/house.png', className: 'bottom-4 right-14 w-9' },
];
